import placeHolderImage from "../images/placeholder.jpg";
export const recipes = [
  {
    id: 1,
    name: "Jollof Rice",
    shortDescription: "A tomato-based Nigerian rice dish.",
    description:
      "Jollof Rice is a popular Nigerian rice dish cooked in a rich tomato and pepper sauce. It is often served with fried plantain, chicken, or salad.",
    categories: ["lunch", "dinner", "vegetarian"],
    prepTime: 20,
    cookTime: 60,
    servings: 5,
    ingredients: [
      "Rice",
      "Tomatoes",
      "Red bell peppers",
      "Onion",
      "Scotch bonnet",
    ],
    steps: [
      "Blend the tomatoes, peppers, and onion.",
      "Cook the pepper mixture with oil and seasoning.",
      "Add washed rice and enough stock or water.",
      "Cover and cook on low heat until the rice is soft.",
      "Fluff the rice and serve warm.",
    ],
    image: placeHolderImage,
  },
  {
    id: 2,
    name: "Fried Rice",
    shortDescription: "A colourful rice dish cooked with vegetables.",
    description:
      "Nigerian Fried Rice is a flavourful rice dish cooked with mixed vegetables and seasoning. It is commonly served at parties with chicken, plantain, or salad.",
    categories: ["lunch", "dinner"],
    prepTime: 20,
    cookTime: 35,
    servings: 4,
    ingredients: ["Rice", "Mixed vegetables", "Onion", "Stock", "Curry powder"],
    steps: [
      "Parboil the rice until partly cooked.",
      "Fry onions and vegetables with seasoning.",
      "Add the rice and stock gradually.",
      "Stir and cook until the rice is soft.",
      "Serve warm with your preferred side.",
    ],
    image: placeHolderImage,
  },
  {
    id: 3,
    name: "Suya",
    shortDescription: "Spicy grilled beef skewers.",
    description:
      "Suya is a popular Nigerian street food made from thinly sliced beef coated in a spicy peanut-based seasoning. It is often served with onions, tomatoes, and extra pepper.",
    categories: ["snacks", "dinner"],
    prepTime: 25,
    cookTime: 20,
    servings: 4,
    ingredients: ["Beef", "Suya spice", "Oil", "Onion", "Tomatoes"],
    steps: [
      "Slice the beef thinly and place onto skewers.",
      "Brush lightly with oil.",
      "Coat the beef with suya spice.",
      "Grill until cooked through and slightly charred.",
      "Serve with sliced onions and tomatoes.",
    ],
    image: placeHolderImage,
  },
  {
    id: 4,
    name: "Puff Puff",
    shortDescription: "Sweet deep-fried dough balls.",
    description:
      "Puff Puff is a soft and sweet Nigerian snack made from a simple yeast dough. It is often served at parties, gatherings, or as a quick treat.",
    categories: ["snacks", "dessert", "vegetarian"],
    prepTime: 15,
    cookTime: 20,
    servings: 6,
    ingredients: ["Flour", "Sugar", "Yeast", "Water", "Oil"],
    steps: [
      "Mix flour, sugar, yeast, and warm water into a soft batter.",
      "Cover and allow the batter to rise.",
      "Heat oil in a deep pan.",
      "Scoop small portions into the hot oil.",
      "Fry until golden brown and drain before serving.",
    ],
    image: placeHolderImage,
  },
  {
    id: 5,
    name: "Egusi Soup",
    shortDescription: "A rich soup made with ground melon seeds.",
    description:
      "Egusi Soup is a hearty Nigerian soup made with ground melon seeds, leafy greens, and assorted seasoning. It is commonly eaten with swallows such as pounded yam, eba, or amala.",
    categories: ["lunch", "dinner"],
    prepTime: 25,
    cookTime: 45,
    servings: 5,
    ingredients: ["Ground egusi", "Spinach", "Palm oil", "Onion", "Stock"],
    steps: [
      "Prepare the egusi paste with water and seasoning.",
      "Heat palm oil and fry onions.",
      "Add the egusi mixture and cook until thickened.",
      "Add stock and leafy greens.",
      "Simmer until the soup is rich and fully cooked.",
    ],
    image: placeHolderImage,
  },
];
