/*

imageCredit: "Photo by pixzolo-photography fron Upsplash"
}


*/

import jollofRiceImage from "../images/jollof-rice.jpg";
import friedRiceImage from "../images/fried-rice.jpg";
import puffPuffImage from "../images/puff-puff.jpg";
import suyaImage from "../images/suyaImage.jpg";
import egusiSoupImage from "../images/egusiSoupImage.jpg";
import yamAndEggImage from "../images/yamAndEggImage.jpg";
import papImage from "../images/papImage.jpg";
import beefStewImage from "../images/beefStewImage.jpg";
import meatPieImage from "../images/meatPieImage.jpg";
import bunsImage from "../images/bunsImage.jpg";
import plantainImage from "../images/plantainImage.jpg";
export const recipes = [
  {
    id: 1,
    name: "Jollof Rice",
    shortDescription:
      "A rich tomato-based rice dish cooked with peppers, onions, and spices.",
    description:
      "Jollof Rice is a popular West African one-pot rice dish made with a tomato and pepper sauce, onions, stock, and seasoning. It is commonly served at parties, celebrations, and family meals, and can be enjoyed on its own or with sides such as plantain or salad and with protein like meat or chicken.",
    categories: ["lunch", "dinner", "vegetarian"],
    prepTime: 25,
    cookTime: 75,
    servings: 5,
    ingredients: [
      "3 cups long-grain rice ",
      "4 medium tomatoes",
      "2 red bell peppers",
      "1 scotch bonnet pepper",
      "1 large onion",
      "3 tablespoons tomato paste",
      "1/4 cup vegetable oil",
      "2 cups vegetable stock",
      "1 cup water",
      "2 tablespoon curry powder",
      "1 teaspoon dried thyme",
      "1 bay leaf",
      "1 teaspoon paprika",
      "6 maggi seasoning tablets",
      "Salt to taste",
    ],
    instructions: [
      "Blend the tomatoes, red bell peppers, scotch bonnet, and half of the onion until smooth.",
      "finely chop the remaining onion.",
      "Heat the vegetable oil in a large pot over medium heat.",
      "fry the onion in the oil until soft and fragrant.",
      "Add the tomato paste and cook for 10 minutes, stirring often so it does not burn.",
      "Pour in the blended pepper mixture.",
      "Set the heat to low and season with curry powder, thyme, bay leaf, paprika, seasoning tablets, and salt.",
      "Cook the pepper mixture on medium heat for 15-20 minutes or until the pepper mix thickens.",
      "While that is cooking rinse the rice several times until the water runs mostly clear, then drain and set aside.",
      "Add the vegetable stock and water, then stir well.",
      "Add the drained rice and stir until the rice is coated in the sauce.",
      "Cover the pot tightly with foil covering the pot and cook on low heat until the rice is tender and the liquid has absorbed.",
      "Check every 10 minutes and  it should be ready in around 30-40 minutes but add a small splash of water if the rice needs more time to soften and the pot is dry.",
      "Once ready turn off the heat and add a table spoon of oil and mix it in then let the rice steam for 5 minutes.",
    ],
    image: jollofRiceImage,
    imageAlt: "A plate of Nigerian Jollof Rice",
    imageCredit: "Photo by keesha-s-kitchen from Upsplash",
  },
  {
    id: 2,
    name: "Nigerian Fried Rice",
    shortDescription:
      "A colourful rice dish cooked with stock, curry powder, vegetables, and protein.",
    description:
      "Nigerian Fried Rice is a popular party-style rice dish made with seasoned stock, curry powder, mixed vegetables, and protein such as turkey, chicken, or beef liver. It is known for its bright colour, savoury flavour, and crunchy vegetables, and is often served at celebrations with plantain, coleslaw, or grilled meat.",
    categories: ["lunch", "dinner"],
    prepTime: 45,
    cookTime: 50,
    servings: 6,
    ingredients: [
      "5 cups basmati rice or long-grain parboiled rice",
      "4 cups seasoned turkey or chicken stock",
      "1 cup water",
      "2 teaspoons curry powder",
      "1 seasoning cube",
      "1 green bell pepper, diced",
      "3 large carrots, diced",
      "1 cup sweet corn",
      "1 handful green beans, chopped",
      "1 bunch spring onions, chopped",
      "1 onion, chopped",
      "1 thumb-sized piece ginger, grated",
      "2 habanero peppers, finely chopped",
      "3 tablespoons butter",
      "1/4 cup vegetable oil",
      "1 teaspoon white pepper",
      "500g cooked beef liver, diced",
      "Salt to taste",
    ],
    instructions: [
      "Rinse the rice several times until the water runs mostly clear, then drain it well.",
      "Add the rice to a pot with butter and lightly fry it for a few minutes to help keep the grains separate.",
      "Pour in the seasoned stock, water, curry powder, seasoning cube, and diced green bell pepper.",
      "Cook the rice until it is mostly done but still firm enough to stir-fry later.",
      "Spread the rice out or leave it uncovered for a short time so it cools slightly and does not clump.",
      "Prepare the vegetables by dicing the carrots, chopping the green beans, slicing the spring onions, and draining the sweet corn if using canned corn.",
      "Heat vegetable oil in a large pan or wok, then add the onion and grated ginger.",
      "Add the sweet corn, green beans, bell pepper, habanero, carrots, and white pepper.",
      "Stir-fry the vegetables briefly so they stay colourful and slightly crunchy.",
      "Add the diced cooked liver and stir it through the vegetables.",
      "Add the cooked rice in batches and stir-fry until the rice, vegetables, and protein are evenly mixed.",
      "Taste and adjust the seasoning with salt or extra seasoning if needed.",
      "Garnish with spring onions and serve warm with plantain, coleslaw, or grilled protein.",
    ],
    image: friedRiceImage,
    imageAlt: "A plate of Nigerian Fried Rice with mixed vegetables",
    imageCredit: "Photo by pixzolo-photography from Upsplash",
  },
  {
    id: 3,
    name: "Puff Puff",
    shortDescription:
      "Soft, sweet fried dough balls made with flour, yeast, sugar, and nutmeg.",
    description:
      "Puff Puff is a popular Nigerian snack made from a simple yeast-based batter that is left to rise before being fried until golden brown. It is soft and airy inside, slightly crisp on the outside, and often served at parties, family gatherings, or as part of small chops.",
    categories: ["snacks", "desserts"],
    prepTime: 60,
    cookTime: 15,
    servings: 6,
    ingredients: [
      "2 cups all-purpose flour",
      "1/4 cup sugar",
      "1 teaspoon instant yeast",
      "1/2 teaspoon nutmeg",
      "1 pinch salt",
      "3/4 to 1 cup lukewarm water",
      "2 tablespoons milk, optional",
      "Vegetable oil for frying",
    ],
    instructions: [
      "Add the flour, sugar, instant yeast, nutmeg, and salt to a large bowl.",
      "Pour in the lukewarm water gradually while mixing until a thick, stretchy batter forms.",
      "Add the milk if using, then mix again until the batter is smooth.",
      "Cover the bowl with a clean towel or plastic wrap.",
      "Leave the batter in a warm place until it rises and becomes airy.",
      "Heat vegetable oil in a deep pan over medium-low heat.",
      "Scoop small portions of the batter and carefully drop them into the hot oil.",
      "Fry in batches, turning the puff puff so each side browns evenly.",
      "Remove from the oil once golden brown and cooked through.",
      "Drain on paper towels and serve warm, plain or with a sweet or spicy dip.",
    ],
    image: puffPuffImage,
    imageAlt: "Golden Nigerian Puff Puff served in a bowl",
    imageCredit: "Photo by keesha-s-kitchen from Upsplash",
  },
  {
    id: 4,
    name: "Suya",
    shortDescription:
      "Spicy Nigerian beef skewers coated in yaji spice and grilled until tender.",
    description:
      "Suya is a popular Nigerian street food made with thin slices of beef coated in a bold peanut-based yaji spice mix, then grilled or roasted on skewers. It is often served with sliced onions, tomatoes, cucumbers, and extra suya spice.",
    categories: ["lunch", "dinner", "snacks"],
    prepTime: 75,
    cookTime: 25,
    servings: 6,
    ingredients: [
      "700g beef steak, thinly sliced",
      "1/2 teaspoon salt",
      "1/2 teaspoon beef or chicken bouillon powder",
      "1 tablespoon peanut oil or neutral cooking oil",
      "1/2 cup suya spice, plus extra for serving",
      "Cayenne pepper, optional",
      "Sliced onions, to serve",
      "Sliced tomatoes, to serve",
      "Sliced cucumber, to serve",
    ],
    instructions: [
      "Soak wooden skewers in water for at least 20 minutes so they do not burn during cooking.",
      "Slice the beef as thinly as possible, then cut it into smaller pieces suitable for skewering.",
      "Season the beef with salt, bouillon powder, optional cayenne pepper, and oil.",
      "Cover the seasoned beef and marinate in the fridge for at least 55 minutes.",
      "Thread the beef pieces onto skewers, keeping the pieces close together so they stay juicy.",
      "Coat the skewered beef generously with suya spice on both sides.",
      "Place the skewers on a rack or lined tray and cook at 200°C for about 20–25 minutes, turning halfway through.",
      "Serve hot with sliced onions, tomatoes, cucumber, and extra suya spice.",
    ],
    image: suyaImage,
    imageAlt:
      "Nigerian suya beef skewers served with onions, tomatoes, and cucumber",
    imageCredit: "Photo by Deborah silveira from Pexels",
  },
  {
    id: 5,
    name: "Egusi Soup",
    shortDescription:
      "A rich Nigerian melon seed soup cooked with meat, fish, palm oil, peppers, and leafy greens.",
    description:
      "Egusi Soup is a hearty Nigerian soup made with ground melon seeds, assorted meat, fish, palm oil, peppers, and leafy greens. It has a thick, savoury texture and is commonly served with swallow foods like pounded yam, eba, fufu, or sometimes rice.",
    categories: ["lunch", "dinner"],
    prepTime: 45,
    cookTime: 30,
    servings: 6,
    ingredients: [
      "2 cups ground egusi melon seeds",
      "500g goat meat or assorted meat",
      "Stockfish, soaked and cleaned",
      "Dried catfish, cleaned and deboned",
      "1/2 cup palm oil",
      "2 red bell peppers",
      "2 scotch bonnet peppers",
      "1 onion",
      "1 tablespoon ground crayfish",
      "1 tablespoon locust beans, optional",
      "1 seasoning cube",
      "Salt, to taste",
      "1 cup chopped uziza leaves or spinach",
      "Water or meat stock, as needed",
    ],
    instructions: [
      "Season the meat with salt, seasoning cube, and some chopped onion, then boil until tender.",
      "Add the cleaned stockfish to the pot and continue cooking until softened.",
      "Blend the bell peppers, scotch bonnet peppers, and onion into a rough pepper mixture.",
      "Mix the ground egusi with a small amount of water or stock to form a thick paste.",
      "Heat palm oil in a pot, then add small spoonfuls of the egusi paste and allow them to fry gently until they begin to form lumps.",
      "Remove the fried egusi lumps and set them aside.",
      "In the same pot, add the blended pepper mixture, crayfish, and locust beans, then cook until the sauce reduces and becomes fragrant.",
      "Pour in some meat stock, then return the fried egusi lumps, cooked meat, stockfish, and dried catfish to the pot.",
      "Simmer the soup gently until the egusi thickens the broth and the flavours combine.",
      "Add the chopped uziza leaves or spinach, stir gently, and cook for a few more minutes before serving.",
    ],
    image: egusiSoupImage,
    imageAlt:
      "A bowl of Nigerian egusi soup made with melon seeds, meat, fish, and leafy greens",
    imageCredit: "Photo by Tosan Dundun from Upsplash",
  },
  {
    id: 6,
    name: "Yam and Egg",
    shortDescription:
      "Boiled yam served with a savoury Nigerian egg sauce made with tomatoes, peppers, and onions.",
    description:
      "Yam and Egg is a popular Nigerian breakfast dish made with soft boiled yam and a rich egg sauce cooked with tomatoes, peppers, onions, and simple seasonings. It is filling, comforting, and commonly eaten for breakfast or brunch.",
    categories: ["breakfast", "lunch"],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    ingredients: [
      "Yam, enough for about 8 slices",
      "4-6 large eggs",
      "2 medium tomatoes, chopped",
      "1-2 scotch bonnet peppers, chopped",
      "1 small onion, chopped",
      "1 red bell pepper, chopped",
      "1/3 cup vegetable oil",
      "1 teaspoon salt for boiling the yam",
      "1/2 teaspoon salt for the egg sauce",
      "1 seasoning cube",
      "1/2 teaspoon curry powder",
      "1/2 teaspoon thyme",
    ],
    instructions: [
      "Slice the yam into thick rounds, peel off the skin, and rinse until the water runs clear.",
      "Place the yam pieces in a pot, add enough water to cover them, season with salt, and boil over medium heat until soft.",
      "Check the yam with a fork, then drain the water once the pieces are tender.",
      "Break the eggs into a bowl, add a little salt, and whisk until the yolks and whites are fully combined.",
      "Heat vegetable oil in a frying pan over medium-low heat.",
      "Add the chopped tomatoes, scotch bonnet peppers, onion, and red bell pepper, then cook for a few minutes until softened.",
      "Season the sauce with salt, seasoning cube, curry powder, and thyme, then stir well.",
      "Pour the whisked eggs into the sauce and leave briefly so the eggs begin to set.",
      "Stir gently until the eggs are cooked through but still soft.",
      "Serve the egg sauce warm with the boiled yam.",
    ],
    image: yamAndEggImage,
    imageAlt:
      "Boiled yam served with Nigerian egg sauce made with tomatoes, peppers, and onions",
    imageCredit: "Photo by mk_photoz from Pexels",
  },
  {
    id: 7,
    name: "Pap",
    shortDescription:
      "A smooth Nigerian fermented cereal porridge, often served warm with milk, sugar, or akara.",
    description:
      "Pap, also known as ogi or akamu, is a smooth fermented cereal porridge commonly eaten for breakfast in Nigeria. It is light, comforting, and often served warm with milk and sugar, or paired with sides like akara, moi moi, beans, or puff puff.",
    categories: ["breakfast", "vegetarian"],
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    ingredients: [
      "1/2 cup ogi or pap paste",
      "1/4 cup room-temperature water",
      "2 to 2 1/2 cups boiling water",
      "Milk, optional, to serve",
      "Sugar or honey, optional, to serve",
    ],
    instructions: [
      "Place the pap paste in a bowl and add the room-temperature water.",
      "Mix until the paste becomes smooth and lump-free, with a texture similar to thick cream.",
      "Bring the water to a rolling boil in a kettle or pot.",
      "Stir the pap mixture again, as the starch can settle quickly.",
      "Slowly pour the boiling water into the pap mixture while stirring continuously.",
      "Keep stirring until the mixture thickens and becomes smooth and glossy.",
      "If the pap is too thick, add a little more hot water until it reaches your preferred consistency.",
      "Serve warm with milk, sugar, or honey if desired.",
    ],
    image: papImage,
    imageAlt: "A bowl of smooth Nigerian pap served warm with a creamy texture",
    imageCredit: "Photo by Tochukwu Ekeh from Pexels",
  },
  {
    id: 8,
    name: "Nigerian Beef Stew",
    shortDescription:
      "A rich Nigerian tomato and pepper stew cooked with tender beef and warm spices.",
    description:
      "Nigerian Beef Stew is a classic tomato-based stew made with beef, blended peppers, tomatoes, onions, garlic, ginger, and spices. It is rich, savoury, slightly spicy, and commonly served with rice, fried plantain, yam, beans, pasta, or bread.",
    categories: ["lunch", "dinner"],
    prepTime: 15,
    cookTime: 30,
    servings: 8,
    ingredients: [
      "900g beef, cut into pieces",
      "1 medium onion, diced",
      "1 bay leaf",
      "1 teaspoon curry powder",
      "1 teaspoon dried thyme or rosemary",
      "2 teaspoons beef or chicken bouillon powder",
      "Salt, to taste",
      "1 cup water, or as needed",
      "2 large red bell peppers",
      "1-3 scotch bonnet peppers",
      "4 medium plum tomatoes",
      "1 large onion",
      "3 garlic cloves",
      "1/2 inch fresh ginger",
      "1/4 cup palm oil",
      "1/4 cup vegetable oil or olive oil",
      "2 tablespoons tomato paste",
      "1 to 1 1/2 cups beef stock",
      "1 teaspoon dried thyme",
      "1 teaspoon curry powder",
      "1 teaspoon beef or chicken bouillon powder",
    ],
    instructions: [
      "Rinse the beef and place it in a large pot with diced onion, bay leaf, curry powder, thyme or rosemary, bouillon powder, salt, and water.",
      "Cover and cook the beef over medium heat until tender, then separate the cooked beef from the stock and reserve the stock for the stew.",
      "Blend the red bell peppers, scotch bonnet peppers, plum tomatoes, onion, garlic, ginger, and tomato paste until smooth.",
      "Heat the palm oil and vegetable oil in a large pot over medium heat.",
      "Add sliced or diced onion to the hot oil and cook for a few minutes until softened.",
      "Pour in the blended pepper and tomato mixture, then cook while stirring occasionally until the sauce reduces and the raw pepper taste cooks out.",
      "Add some reserved beef stock, curry powder, thyme, and bouillon powder, then stir well.",
      "Add the cooked beef back into the stew and simmer until the sauce thickens and the beef absorbs the flavour.",
      "Taste and adjust the salt if needed.",
      "Serve warm with white rice, fried plantain, boiled yam, beans, pasta, or bread.",
    ],
    image: beefStewImage,
    imageAlt:
      "Nigerian beef stew served in a bowl with rich red tomato and pepper sauce",
    imageCredit: "Photo by VK Bro from Upsplash",
  },
  {
    id: 9,
    name: "Nigerian Meat Pie",
    shortDescription:
      "A flaky Nigerian pastry filled with seasoned minced beef, potatoes, and carrots.",
    description:
      "Nigerian Meat Pie is a popular savoury pastry filled with minced beef, potatoes, carrots, onions, and warm spices. It has a golden crust and a soft, flavourful filling, making it a common snack for parties, lunchboxes, and everyday treats.",
    categories: ["snacks", "lunch"],
    prepTime: 60,
    cookTime: 20,
    servings: 15,
    ingredients: [
      "1 1/2 tablespoons vegetable oil",
      "1/2 cup onion, diced",
      "450g ground beef or minced beef",
      "1 cup carrots, diced",
      "1 cup potatoes, diced",
      "1 teaspoon curry powder",
      "1/2 teaspoon thyme",
      "2 bouillon cubes",
      "1 1/4 teaspoons salt, or to taste",
      "Red chilli flakes or cayenne pepper, optional",
      "1 1/2 to 2 cups water",
      "2 tablespoons flour, for thickening",
      "4 tablespoons water, for slurry",
      "4 cups all-purpose flour",
      "1 teaspoon baking powder, optional",
      "1/2 teaspoon nutmeg, optional",
      "1/2 tablespoon sugar, optional",
      "Pinch of salt",
      "10 tablespoons margarine",
      "10 tablespoons butter",
      "5-7 tablespoons cold water",
      "1 egg, for egg wash",
    ],
    instructions: [
      "Heat the vegetable oil in a pan over medium heat, then add the diced onion and cook until softened.",
      "Add the minced beef and cook until browned, breaking it apart as it cooks.",
      "Season the beef with curry powder, thyme, bouillon, salt, and optional chilli flakes or cayenne pepper.",
      "Add the diced carrots and potatoes, then pour in enough water to help them cook until tender.",
      "Mix the flour and water into a slurry, then stir it into the filling to thicken it. Set the filling aside to cool.",
      "In a large bowl, mix the flour, baking powder, nutmeg, sugar, and salt.",
      "Rub the cold margarine and butter into the flour mixture until it looks like breadcrumbs.",
      "Add cold water a little at a time until a firm dough forms, then rest the dough briefly if needed.",
      "Roll out the dough and cut it into circles.",
      "Place some cooled filling in the centre of each circle, fold over, and seal the edges with a fork.",
      "Brush the pies with egg wash, then make small holes or slits so steam can escape.",
      "Bake at 180°C or 350°F for about 20-30 minutes, or until golden brown.",
    ],
    image: meatPieImage,
    imageAlt:
      "Nigerian meat pies with golden pastry filled with minced beef, potatoes, and carrots",
    imageCredit: "Photo by Ozichi Ogbu on Pexels",
  },
  {
    id: 10,
    name: "Nigerian Buns",
    shortDescription:
      "Sweet fried Nigerian buns with a slightly crisp outside and soft, dense centre.",
    description:
      "Nigerian Buns are sweet fried dough balls that are slightly crisp on the outside and soft on the inside. Unlike puff puff, buns are made with baking powder instead of yeast, so they are quicker to prepare and are often enjoyed as a snack or breakfast treat with tea.",
    categories: ["snacks", "breakfast", "desserts"],
    prepTime: 10,
    cookTime: 10,
    servings: 20,
    ingredients: [
      "3 cups all-purpose flour",
      "1/4 cup sugar",
      "2 teaspoons baking powder",
      "1/4 teaspoon salt",
      "1/2 teaspoon nutmeg, optional",
      "3 eggs",
      "1/4 cup butter, melted",
      "3/4 cup milk",
      "Vegetable oil, for deep frying",
    ],
    instructions: [
      "Add the flour, sugar, baking powder, salt, and optional nutmeg to a large bowl, then mix until combined.",
      "Add the eggs, melted butter, and milk to the dry ingredients.",
      "Mix everything together until a thick batter forms.",
      "Heat vegetable oil in a deep pan over medium heat until hot enough for frying.",
      "Scoop small portions of the batter into the hot oil, making sure not to make the buns too large.",
      "Fry the buns, turning them as needed, until they are golden brown on all sides and cooked through.",
      "Remove the buns from the oil and place them on paper towels or a cooling rack to drain excess oil.",
      "Serve warm or at room temperature.",
    ],
    image: bunsImage,
    imageAlt: "Golden Nigerian buns with a crisp outside and soft centre",
    imageCredit: "Photo by Mak on Unsplash",
  },
  {
    id: 11,
    name: "Fried Plantain",
    shortDescription:
      "Sweet ripe plantain slices fried until golden, caramelised, and tender.",
    description:
      "Fried Plantain, also known as dodo in Nigeria, is made by slicing ripe plantains and frying them until the edges caramelise and the centres become soft and sweet. It is commonly served as a side with rice, stew, beans, eggs, or enjoyed on its own as a simple snack.",
    categories: ["breakfast", "lunch", "dinner", "snacks", "vegetarian"],
    prepTime: 5,
    cookTime: 10,
    servings: 4,
    ingredients: [
      "2 large ripe plantains",
      "Vegetable oil, for frying",
      "Salt, optional",
    ],
    instructions: [
      "Cut off both ends of each plantain, then make a shallow slit along the peel.",
      "Remove the peel carefully and place the plantains on a chopping board.",
      "Slice the plantains diagonally into medium-thick pieces so they cook evenly.",
      "Heat vegetable oil in a frying pan over medium heat.",
      "Add the plantain slices in a single layer, making sure not to overcrowd the pan.",
      "Fry for a few minutes on one side until golden brown, then flip and cook the other side.",
      "Remove the fried plantain from the oil and drain on kitchen paper or a cooling rack.",
      "Sprinkle lightly with salt if desired and serve warm.",
    ],
    image: plantainImage,
    imageAlt: "Golden fried ripe plantain slices served on a plate",
    imageCredit: "Photo by SC Studio on Pexels",
  },
];
